export const ROMAN_URDU_BODIES: readonly string[] = [
  "Living room ke liye medium size order kiya tha. Gold ka kaam photos se zyada rich lagta hai, frame bhi mazboot hai.",
  "Parents ke namaz ke kamre ke liye gift kiya. Composition reverent hai lekin bhari nahi, packaging bhi bohot achi thi.",
  "Pehle online art se thora dar lag raha tha, lekin canvas bilkul tight aur crease-free aaya. Script ka balance bohot acha hai.",
  "Entry console ke upar lagaya hai. Guests turant notice karte hain, parchment tone hamare oak flooring se achi match karti hai.",
  "Interior designer hoon aur usually custom calligraphy specify karta hoon. Ye piece last year ki hand-commissioned work ke saamne khara rehta hai.",
  "Large format ne woh khali wall fill kar di jo hum treat nahi kar pa rahe thay. Edges clean hain aur gilt evening light mein cheap nahi lagti.",
  "Study ke liye chhota size liya. Intimate hai lekin timid nahi — aisi cheez jo sirf glance nahi, baith kar dekhi jati hai.",
  "WhatsApp par framing consult practical thi. Unhon ne mujhe sofa ke saamne bada size lene se rok diya, honesty ki qadar hai.",
  "Colour fidelity achi hai. Marbled ground mein depth hai, flat print jaisi nahi jo aksar calligraphy prints mein hoti hai.",
  "Office shift par colleague ko gift kiya. Same day reply aaya ke piece serious lagti hai, decorative clutter nahi.",
  "Teen ateliers se compare kiya tha. Inhon ne negative space samjha, verse ko edges tak cram nahi kiya.",
  "Delivery estimate se do din late hui, lekin pehle hi message aa gaya tha. Kaam khud faultless tha, thori wait worth thi.",
  "Window ke saamne lagaya tha, glare ki fikar thi. Surface matte enough hai ke afternoon mein bhi script readable rehti hai.",
  "Gold leaf candlelight mein gatherings ke dauran pakadti hai. Chillati nahi, bas room ko hold karti hai.",
  "Sunday evening framing question ka jawab mil gaya. Piece ke saath care card bhi aaya jo maine rakha hai.",
  "Clinic waiting room mein lagaya. Patients comment karte hain, purane abstract prints se zyada effective hai.",
  "Crate thora oversized tha courier ke liye, lekin andar kuch bhi shift nahi hua. Foam aur double box — transit seriously liya.",
  "Contemporary apartment ke liye fikar thi ke verse zyada formal lagega. Nahi laga, mid-century furniture ke saath acha baithta hai.",
  "Medium size sahi choice thi. Chhota wall par kho jata, bara window se compete karta. Listing photos achi thi lekin advice zyada helpful thi.",
  "Wedding gift diya, couple ne baraat hall photos mein display kiya. Quiet endorsement jaisa laga.",
  "Kufic floral work disciplined hai. Leaves aur letterforms ka weight share karta hai, fight nahi karte.",
  "Discount week mein order kiya, lekin full price par bhi dubara le leta. Reduction bonus tha, reason nahi.",
  "Lahore ki humid July ke baad stretcher bars mein bowing nahi aayi. Kiln-dried jaisa behave karta hai.",
  "Saas ne letter spacing par pause kiya, phir sir hilaya. Mujhe wohi review chahiye tha.",
  "Boutique hotel corridor ke liye chahiye tha jo photo achi ho. Teen metre aur close dono se achi lagti hai.",
  "Parchment ground mein warmth hai jo cheap prints kabhi theek nahi karte. Thori lived-in feel deti hai.",
  "Dispatch se pehle actual piece ki teen photos bheji, daylight mein, bina filter ke. Respect.",
  "Box se nikalte hi level tha. Spirit level use kiya phir bhi, already true tha.",
  "Instagram page months se dekh raha tha. Physical object feed se behtar hai, yehi sahi order hai.",
  "Law office reception mein lagaya. Clients assume karte hain antique hai, hum turant correct nahi karte.",
  "Wire picture-grade hai, woh patli cheez nahi jo ek saal mein snap ho jati hai.",
  "Toronto se order kiya, customs paperwork included thi. Door par surprise fees nahi aayi.",
  "Atelier ne complete sentences mein jawab diya. Emoji aur sirf tracking number wali shops se farq hai.",
  "Size chart millimetre tak accurate tha. Teen dafa measure kiya tha, rare hai aur notable bhi.",
  "Karachi courier ne pehle inspect karne ko kaha. Shop ne clearly brief kiya tha unhe.",
  "Gold leaf application thin aur even hai, costume jewellery jaisi nahi. Main sceptical tha contemporary canvas par.",
  "Stairwell mein lagaya jahan log slow down karte hain. Is piece ke liye sahi architecture hai.",
  "Bhai ne pehle lithograph samjha jab tak close nahi khada. Surface variation achi tarah batati hai.",
  "Room describe karne par different verse suggest kiya, advice li. Result considered lagta hai, catalogue nahi.",
  "Frame profile slim hai jo work ko contemporary rakhti hai. Heavy moulding hotel-lobby territory mein le jati.",
  "Arabic padh leta hoon, hesitant letter notice karta hoon. Yahan koi nahi, haath trained hai.",
  "Boardroom ke liye chahiye tha jo map ya slogan na ho. Calligraphy adult choice thi, ye piece khaas.",
  "Unboxing ceremonial feel deti hai bina precious ke. Tissue, plastic nahi — pehle paanch minute ka khayal hai.",
  "Do bachon ke saath ghar hai. Piece high enough hai aur varnish fingerprints invite nahi karti.",
  "2019 Istanbul piece se compare kiya, colour par hold karta hai. Price ke hisaab se zyada satisfied hoon.",
  "Evening west light ground ko warm karti hai, subah cool. Static photo se zyada interesting rehna hai.",
  "Authenticity certificate signed aur dated aaya, generic PDF nahi. Size specific tha.",
  "Biwi ne piece choose kiya, main logistics handle kiya. Art par pehli dafa argument nahi hui.",
  "Kufic panel mein garden logic hai, poster logic nahi. Motifs grow karte hain, stamp nahi.",
  "Gallery hooks se lagaya plaster wall par. Piece drift nahi hui, weight distribution achi hai.",
  "Blacks ink-dark hain, charcoal-grey nahi. Pichle saal doosri shop se print return kiya tha isi wajah se.",
  "Medium canvas sleeper size hai. Na zyada proud, na apologetic. Zyada tar living rooms yahi chahte hain.",
  "Family WhatsApp par photo bheji, aunties ne approve kiya. Hamare ghar mein serious metric hai.",
  "Manuscript restore karne wale dost ne proportions classical kaha. Star rating se zyada trust kiya.",
  "Deep olive wall paint ke baad piece choose kiya. Room ke liye lagta hai jaise wait kar raha tha.",
  "Islamabad delivery weekday morning promised thi, hit hui. Raat das baje rider theatre nahi hua.",
  "Motivational quotes dressed as art pasand nahi. Ye scripture hai craft ke saath, alag category.",
  "Stretcher keys present hain, seasons ke baad true kar sakta hoon. Professional habit.",
  "1970s family photo ke saath lagaya, ek doosre se baat karte hain. Design karna is se mushkil hai.",
  "Marketplace se sasta print almost liya tha. Presence ka gap embarrassing hai, real surface ke liye pay karo.",
  "Gold light ke taur par use hui hai, luxury signalling nahi. Farq feel hota hai chahe naam na do.",
  "Housekeeper ne dry cloth se dust poochha. Care card pehle hi yes keh chuka tha.",
  "Saath saal ka hoon, trends se thak gaya hoon. Ye piece trends mein participate nahi karti.",
  "Large format hang karne ke liye do log chahiye. Instructions useful thi, kisi industry mein rare.",
  "Letter endings properly taper hain. Font wale designer aur calligrapher ka farq yahi hai.",
  "DHA mein dost ke ghar similar work dekhi, studio dhundhne mein ek hafta laga. Worth tha.",
  "Linseed ki halki smell aayi jo ek din mein gayab ho gayi. Authentic, chemical nahi.",
  "Unique ya edition clear bataya. Transparency adjectives se tez trust banati hai.",
  "Frame corners mitred cleanly hain. Fingernail se join par kuch catch nahi hua.",
  "Faded tapestry ki jagah lagaya, wall phir se awake lagti hai.",
  "Chhota size picture ledge par books ke saath baithta hai. Spines se compete nahi karta.",
  "Ek lamp, raat, ye canvas. Room ka focal point finally TV nahi hai.",
  "Dispatch note par naam sahi spell tha. Notice karta hoon jab galat hota hai.",
  "Riyadh mein behn ke liye liya, majlis ki photo bheji. Scale pehli dafa sahi tha.",
  "Glossy finish ki expectation thi, return kar deta. Matte sahi decision thi aur unhon ne stick kiya.",
  "High ceilings hain, large size phir bhi stranded nahi lagta. Internal architecture enough hai.",
  "Teenager ne kaha actually nice hai. Us demographic se standing ovation hai.",
  "Crate rakha hai, agar city change hui to travelling case ready hai. Forward thinking.",
  "Gold uniform nahi hai jo leaf honi chahiye. Machine-flat metallic paint alag cheez hai.",
  "Studio pickup straightforward thi, daylight mein inspect kiya, chai offer hui.",
  "Payment ke baad vanish karne wale calligraphers se deal kiya hai pehle. Yahan confirm, pack, follow through hua.",
  "Verse thora off-centre intentional lagta hai. Dynamic hai, static nahi. Tension ke saath rehna pasand hai.",
  "Wool rug neeche, ye upar. Dono mein handmade grain hai, room cohere karta hai.",
  "Warranty language plain thi, transit damage se bachne wala act of God paragraph nahi. Adult communication.",
  "Pehle owner ki clock ki jagah lagaya. Time ab bhi mark hota hai, bas alag tareeqe se.",
  "Medium crate par barely-there scuff thi, work par kuch nahi. Packing margins generous thay.",
  "Subah kabhi verse dubara padhta hoon. Object second look earn karta hai, wall par words ka point yahi hai.",
  "Designer statement chahta tha, main quiet. Is par compromise hui, dono ko mila jo chahiye tha.",
  "Warm ground par black ink stark white se behtar domestic spaces ke liye. Rooms samajhte hain, sirf pages nahi.",
  "Insured shipping extra di, paperwork real thi checkbox nahi. Achhi neend product ka hissa hai.",
  "Floral motifs script ke secondary hain. Hierarchy poori craft hai, yahan hai.",
  "Weekend floor par wall ke against rakh kar dekha, phir hang kiya. Test pass kiya.",
  "Understatement pasand hai, atelier bhi share karta lagta hai. Jab wall poochegi dubara lenge.",
  "Chhota format gift ke liye acha hai kyunki huge wall commitment force nahi karta.",
  "Edges painted hain, float ke liye frame optional. Hum ne frame kiya, options respect hain.",
  "Khandan mein kisi ne calligraphy old-fashioned samjhi thi. Lagne ke baad chup ho gaye.",
  "Straightedge se stretcher check kiya, deviation negligible hai. Studio carpentry afterthought nahi.",
  "Dusk ke baad gold deepen hoti hai. Different hours ke saath rehna real preview hai.",
  "WhatsApp updates factual thay: packed, courier, out for delivery. Motivational filler nahi, perfect.",
  "Guest room mein lagaya taake visitors ko kuch humane mile subah. Feedback consistent aur warm hai.",
  "Busier composition almost choose ki thi. Restraint behtar age karti hai, glad quiet catalogue hai.",
  "Canvas weave fine enough hai ke script se fight nahi karti. Support aur image agree karte hain.",
  "Store discount ke baad bhi pricing art jaisi feel hui, clearance rack nahi.",
  "Baap ne museum wali pose mein dekha, phir price poochi, phir sir hilaya.",
  "Front par QR code ya brand splash nahi. Work ko work rehne diya gaya.",
  "Existing walnut frames ke saath shade confirm kiya, comfortably baithta hai.",
  "Karachi humidity paper ke liye unkind hai. Canvas sahi medium tha, unhon ne pehle hi kaha.",
  "Clean adult purchase thi. Countdown timers aur fake scarcity nahi, bas piece, size, price.",
  "Large work fourteen-foot drawing room wall hold karti hai. Postage stamp ka dar tha, photos honest thay.",
  "Description har sentence mein heritage luxury oversell nahi karti. Object woh labour karti hai.",
  "Frame corners reinforced hain, sirf dekha to pata chala. Zyada tar buyers nahi dekhenge phir bhi benefit hoga.",
  "Eid se pehle lagaya, ghar finished feel hua. Ek rectangle se zyada maangna tha, manage kiya.",
  "Daylight mein blacks flatten hone par pehle art return kiya tha. Ye hold karte hain, pigment load adequate hai.",
  "Catalogue edited lagta hai, sab kuch listed nahi. Listed cheez chosen feel hoti hai.",
  "Partner ke parents Multan se aaye, hum se zyada is par time spend kiya. Allow karenge.",
  "Narrow picture light kaafi thi, theatre rig nahi chahiye. Surface modest lighting ke saath generous hai.",
  "Teen anxious sizes ki bajaye teen serious sizes. Decision dignified rahi.",
  "Script famous historical page mimic nahi karti. Apna tempo hai, novelty-seeking bina originality.",
  "Foam recycle karte waqt guilty feel hua, phir rakha kyunki next move ko chahiye hoga.",
  "Theme household nahi hain. Ek strong piece kaafi hai, ye is saal woh piece hai.",
  "Outdoor covered corridor suitable poocha, no kaha. Boundary respect ki, andar rakha.",
  "Invoice itemised thi discount lines ke saath. Office accounts ne bina chase process kiya.",
  "Do metre pe composition lock hoti hai, bees centimetre pe craft hold karti hai. Dono distances matter karti hain.",
  "Ghar mein zyada beige tha, ye dark introduce kiya. Room ko finally bass note mila.",
  "Site par atelier word use hua, embarrassing nahi. Work language support karti hai.",
  "Algorithm art ke long week ke baad liya, palate cleanser jaisa laga object form mein.",
  "Hanging wire properly twisted hai, single strand hoping nahi. Meri opinions meet hui.",
  "Houston cousin ne hamari dekh kar order kiya, alag piece same standard ke mutabiq uski photos.",
  "Reviews nahi likhta usually. Pichli teen art purchases disappoint hui thi, ye nahi hui is liye likh raha hoon.",
  "Ground colour chai aur ret ke beech hai. Curtains thori different warm hain phir bhi tolerate karti hai.",
  "Quiet luxury overused phrase hai. Object simply well made hai, woh zyada rare aur useful hai.",
  "Islamic art books shelf par neeche, wall aur shelf finally agree karte hain.",
  "Delivery morning slot thi, hit hui. Doosra din off lene ki zaroorat nahi padi.",
  "Cheap varnish smell nahi, ek din baad room jaisi smell. Chhoti apartment mein important hai.",
  "Stretcher depth millimetre figure ke saath aayi float frame plan karne ke liye. Professionals.",
  "Har wall colour nahi chahti, structure chahti hai. Calligraphy ne provide kiya.",
  "Logo plaque add nahi ki, signature peeche jahan honi chahiye.",
  "Dinner night lagaya, conversation piece par food se zyada ruki. Unusual, welcome.",
  "Chhota pehle aaya, baad mein bara order kiya. Dono same care se pack, systems hain luck nahi.",
  "Letterforms mein patience hai jo deadline se rush nahi hoti. Dekh sakte ho ke nahi ki.",
  "Pichla calligraphy print plastic shine tha. Ye mineral quiet hai, alag species.",
  "Laser level use kiya, top edge straight hai. Universe ordered rehta hai.",
  "Point of view hai unka. Har verse, har colourway, har fad nahi. Editing buyer ke liye respect hai.",
  "Corridor mein public se private rooms connect karte hain. Threshold mark karta hai bina sign ke.",
  "Budget zyada tha phir bhi value feel hui arrival par. Sahi surprise hai.",
  "Product page photos thori cooler hain life se. Room mein warmth aati hai, room prefer karta hoon.",
  "Ghar se guzarne ka tareeqa badal gaya, ab is wall ke paas se long way leta hoon.",
  "Frame rebate canvas edge cleanly chhupati hai. Side se view par white flash nahi.",
  "Bees saal art khareeda, thak kar standards slip hote hain. Ye shop slip nahi hui.",
  "Serious hai lekin sombre nahi. Family house mein kaam karti hai, sirf gallery mein nahi.",
  "UV glass ke baare mein poocha, jab help aur jab theatre explain kiya. Glass skip kiya, canvas honest rehti hai.",
  "Ek hafta lounge mein thi, landing par behtar lagi. Good art second thought survive karti hai.",
  "Har purchase par story nahi chahiye. Aaya, described jaisa tha, true hang karti hai. Kaafi hai, aur bohot hai.",
  "Pehla hafta new feel thi, teesre tak ghar ka hissa ban gayi. Behtar outcome hai.",
  "Carpenter dost se frame glance karwaya, joints wall paint se zyada chalenge. Kaafi tha.",
  "Afternoon heat ke liye curtains band, quieter light mein bhi script fully present rehti hai.",
  "Doosre maker ka canvas months mein sag hua tha. Ye season change ke baad drum-tight hai.",
  "Client ke liye liya phir apne liye doosra order kiya. Sab se seedha recommendation hai.",
  "Glance par impress karke inspection par collapse nahi karti. Ulta karti hai, zyada rare hai.",
  "Narrow hallway hai, medium size respect karti hai. Mural jaisa lecture feel nahi.",
  "Guests ko explain karna band kar diya, woh khud conversation start karte hain. Highest compliment hai.",
  "Charcoal sofa ke saath blacks black rehte hain. Bohot black art blue ya brown ho jati hai, ye nahi.",
  "Moisture barrier ke saath pack, monsoon se ship kiya hai pehle lagta hai. Experience dikhta hai.",
  "Invoice care notes ke saath envelope mein rakha, bees saal baad koi khush hoga.",
  "Ghar ki awaz ho to ye lower register hai — measured, adult, shout nahi karti.",
  "Gold ka kaam drawing room ki light mein bilkul alag nikla, photos se behtar. Frame joints bhi clean hain.",
  "Namaz ke waqt is taraf dekhte hi sukoon milta hai. Packaging itni secure thi ke corner protectors ne kaam kiya.",
  "WhatsApp par size discuss kiya, warna galat measurement par regret hota. Team patient thi, pushy nahi.",
  "Doosri local shop se compare kiya tha, yahan letter spacing zyada disciplined hai. Thora expensive hai lekin worth hai.",
  "Delivery rider ne careful handle kiya, lekin tracking update thora late aaya. Piece khud perfect condition mein thi.",
  "Anniversary gift ke taur par commission jaisa feel diya bina custom price ke. Biwi ko bohot pasand aaya.",
  "Prayer room ki chhoti wall par small size ideal tha. Zyada loud nahi, lekin presence hai.",
  "Frame colour listing se thora warm nikla, lekin walnut furniture ke saath blend ho gaya. Overall khush hoon.",
  "Canvas texture haath lagane par feel hoti hai, flat poster nahi. Guests close jaa kar dekhte hain.",
  "Gift wrap request ki thi, simple lekin elegant tha. Eid par de sakte thay bina extra shopping ke.",
  "Living room mein beige sofa ke saath gold accents perfect hain. Room finally complete lagta hai.",
  "Pehli dafa Sultani Arts se liya, packaging dekh kar hi trust build hua. Bubble wrap aur hard corners dono thay.",
  "Size chart par thora confuse hua, lekin WhatsApp voice note se clear ho gaya. Medium sahi tha hamari wall ke liye.",
  "Gold leaf ka shine artificial nahi, natural lagta hai. Doosri online shops ki metallic paint se clear farq hai.",
  "Delivery Friday promise thi, Saturday aayi. Message pehle aa gaya tha, is liye zyada issue nahi hua.",
  "Office cabin ke liye liya, clients baithte hi wall par nazar jati hai. Professional feel deta hai.",
  "Maa ke liye gift, unhon ne keh diya ke asli calligraphy lagti hai print nahi. Unki approval sab se bari hai.",
  "Framing option discuss ki, slim black recommend kiya unhon ne. Hamari modern interior ke saath match karta hai.",
  "Peshawar tak shipping thori lambi thi lekin piece bilkul safe aaya. Double boxing ne faida diya.",
  "Drawing room ki main wall ke liye large liya. Scale honest tha photos mein, disappointed nahi hua.",
  "Compare karte waqt do cheap alternatives reject kiye. Presence ka farq dekh kar decision easy ho gaya.",
  "WhatsApp consult free thi aur genuinely helpful thi, sales pitch nahi lagi. Size downgrade karne ko kaha, sahi tha.",
  "Packaging kholo to tissue aur corner guards dikhte hain, serious art shop ka sign hai. Plastic bag mein nahi aaya.",
  "Ramzan se pehle order kiya taake guest room ready ho. Time par deliver hua, Alhamdulillah.",
  "Gold work thori subtle hai jo mujhe pasand hai, flashy nahi. Evening lamp ke neeche zyada khubsurat lagti hai.",
  "Frame thori moti lag rahi thi chhoti wall par, lekin quality achi hai is liye adjust kar liya. Piece khud excellent hai.",
  "Calligraphy ka flow natural hai, rushed strokes nahi. Quran ayat ko respect ke saath present kiya gaya hai.",
  "Courier ne gate par hi open karne ko kaha inspect karne ke liye. Transparency achi lagi.",
  "Pehle OLX type prints try kiye thay, ab farq samajh aa gaya. Investment ek dafa ki, daily sukoon milta hai.",
  "Sister ko housewarming gift, unke living room ki colour scheme ke mutabiq suggest kiya unhon ne. Perfect fit hui.",
  "Canvas back par proper hanging hardware lagi hui thi, extra drill ki zaroorat nahi padi. Chhota detail, bara farq.",
  "Photos thori bright thi site par, real piece thori soft tone ki hai. Mujhe real zyada pasand aayi.",
  "Customer service ne replacement frame ka option diya jab corner par halki scratch thi crate se. Service achi thi.",
  "Prayer mat ke saamne wall par lagaya, roz namaz mein focus better hota hai. Spiritual ambience ban gaya.",
  "Thori der socha ke online art lena theek hai ya nahi. Ab regret nahi, recommend kar chuka hoon teen logon ko.",
];
