export type ReviewSeed = {
  name: string;
  location: string;
  rating: 3 | 4 | 5;
  body: string;
  daysAgo: number;
};

const NAMES = [
  "Ayesha Rahman", "Imran Qureshi", "Nadia Khalid", "Hassan Malik", "Sara Ahmed",
  "Omar Farooq", "Mehreen Ali", "Bilal Siddiqui", "Hina Shah", "Zain Abbas",
  "Fatima Noor", "Kamran Iqbal", "Rabia Hassan", "Tariq Mahmood", "Sana Javed",
  "Usman Raza", "Amina Tariq", "Faisal Khan", "Lubna Akhtar", "Hamza Sheikh",
  "Mariam Aziz", "Adnan Butt", "Zara Nadeem", "Shahid Anwar", "Iqra Yousaf",
  "Nabeel Hussain", "Samina Qadir", "Asad Mehmood", "Hira Saeed", "Waqas Nisar",
  "Bushra Jamil", "Rizwan Haider", "Maham Iftikhar", "Saadullah Khan", "Nida Parvez",
  "Junaid Aslam", "Kiran Bukhari", "Arif Zaman", "Saba Rehman", "Danish Gul",
  "Anila Majeed", "Haroon Sharif", "Yasmin Chaudhry", "Moiz Alam", "Shazia Pervez",
  "Farhan Saleem", "Tehmina Rauf", "Ibrahim Latif", "Gulrukh Awan", "Salman Zaheer",
  "Areeba Naseer", "Khurram Shahzad", "Mehwish Irfan", "Noman Qazi", "Sadia Munir",
  "Tahir Gill", "Huma Kazmi", "Waleed Anjum", "Rukhsana Baig", "Aliyan Dar",
  "Nashit Fatima", "Qasim Lodhi", "Saima Durrani", "Ehsan Warraich", "Aalia Buksh",
  "Rehan Siddique", "Zunaira Malik", "Shahbaz Cheema", "Komal Afzal", "Mubashir Rana",
  "Iffat Sohail", "Arslan Ghauri", "Nargis Taimoor", "Owais Jahangir", "Fariha Kamal",
  "Jamshed Mir", "Sundas Aftab", "Kashif Niazi", "Hafsa Qureshi", "Naveed Sattar",
  "Ambreen Zaidi", "Shahmir Khan", "Tooba Ijaz", "Asim Bhatti", "Shumaila Riaz",
  "Gohar Mustafa", "Laila Hashmi", "Umer Dastgir", "Noreen Sajjad", "Hamdullah Jan",
  "Aiman Farid", "Saqib Nadeem", "Rida Bukhari", "Tauseef Alam", "Mahnoor Gillani",
  "Irshad Qamar", "Beenish Anwar", "Fawad Tareen", "Shaista Niazi", "Muneeb Ashraf",
  "Kinza Haroon", "Jahangir Sethi", "Anum Rashid", "Shafqat Ellahi", "Hania Qadeer",
  "Rauf Ghaznavi", "Dua Fatima", "Nadeem Chauhan", "Sabeen Arshad", "Yousaf Minhas",
  "Afsheen Rauf", "Iftikhar Niazi", "Mahira Sohail", "Badar Munir", "Zaraib Awan",
  "Nimra Lodhi", "Sohail Qadri", "Hina Waqar", "Azhar Meenai", "Sumbul Raza",
  "Taha Bukhsh", "Ayesha Gill", "Murtaza Shah", "Fizza Haroon", "Noman Elahi",
  "Rabia Chishti", "Shaheryar Malik", "Hoorain Saeed", "Qaiser Niazi", "Mehak Tufail",
  "Asif Gondal", "Sanaullah Riaz", "Aiman Zahra", "Haris Qureshi", "Nida Buksh",
  "Zeeshan Warraich", "Hina Murtaza", "Arham Siddiqui", "Samreen Jaffri", "Faizan Qadir",
  "Maria Taimur", "Shahzad Butt", "Iqra Lodhi", "Nouman Hashmi", "Areesha Kamran",
  "Bilawal Rauf", "Hafsa Meenai", "Usama Cheema", "Zoya Nisar", "Kamran Tareen",
  "Sundus Elahi", "Adil Bukhari", "Mishal Qamar", "Rizwan Minhas", "Ayesha Durrani",
  "Hamza Ghauri", "Tehreem Anjum", "Shahid Lodhi", "Nimra Qazi", "Owais Hashmi",
  "Fatima Cheema", "Junaid Taimoor", "Hira Ghaznavi", "Saad Elahi", "Maham Qadri",
  "Imtiaz Rana", "Sana Warraich", "Haroon Minhas", "Aalia Niazi", "Danish Bukhsh",
  "Kiran Tareen", "Nabeel Hashmi", "Mehreen Qureshi", "Tariq Cheema", "Bushra Elahi",
  "Faisal Minhas", "Lubna Qazi", "Zain Taimur", "Iqra Hashmi", "Usman Qadri",
  "Nadia Warraich", "Hassan Elahi", "Sara Minhas", "Omar Qazi", "Hina Taimur",
  "Bilal Hashmi", "Mariam Qadri", "Adnan Elahi", "Zara Minhas", "Shahid Qazi",
  "Amina Taimur", "Kamran Hashmi", "Rabia Qadri", "Faisal Elahi", "Sana Minhas",
  "Hamza Qazi", "Fatima Taimur", "Imran Hashmi", "Nadia Qadri", "Hassan Elahi Khan",
];

const LOCATIONS = [
  "Lahore", "Karachi", "Islamabad", "Rawalpindi", "Faisalabad",
  "Multan", "Peshawar", "Sialkot", "Gujranwala", "Quetta",
  "Dubai", "Abu Dhabi", "London", "Manchester", "Toronto",
  "Mississauga", "Houston", "Chicago", "Doha", "Riyadh",
];

const BODIES = [
  "Hung this in our dining room last week. The gold work reads richer in person than it did on screen, and the frame is sturdier than most gallery pieces we have bought locally.",
  "Commissioned this as an anniversary gift. The proportions are calm, not ornamental for ornament’s sake, which is exactly what our living room needed.",
  "I was cautious ordering art online, but the canvas arrived taut and uncreased. The script sits with real balance — nothing rushed about the letterforms.",
  "We placed the medium size above a console in the entry. Guests notice it immediately, and the parchment tone matches our oak flooring surprisingly well.",
  "Bought this for my parents’ prayer space. The composition feels reverent without being heavy. Packaging was museum-grade, with corner protectors that actually did their job.",
  "I work in interiors and usually specify custom calligraphy. This piece held its own against a hand-commissioned work we installed last year. Colour is warmer than the photos suggest.",
  "The large format fills a blank wall we never knew how to treat. Edges are clean, the stretcher is true, and the gilt doesn’t look cheap under evening lamps.",
  "Ordered the small size for my study. It is intimate rather than timid — the kind of piece you sit with, not just glance at.",
  "Framing consult over WhatsApp was practical and unhurried. They steered me away from a size that would have dwarfed the sofa. Grateful for that honesty.",
  "Colour fidelity is excellent. The marbled ground has depth rather than a printed flatness, which is where a lot of ‘calligraphy prints’ fall apart.",
  "Gifted this to a colleague moving into a new office. He wrote back the same afternoon. The piece reads serious, not decorative clutter.",
  "Our architect asked where we sourced it. That is the highest compliment I can pass on. Finish on the frame is even, no glue lines, no warping.",
  "I compared three ateliers before buying. This one understood negative space. The verse is given room to breathe instead of being crammed to the edges.",
  "Arrived two days later than the estimate, but they messaged before I had to chase. The work itself is faultless — worth the short wait.",
  "Hung opposite a window and worried about glare. The surface is matte enough that the script stays readable through the afternoon.",
  "My husband is particular about Islamic geometry. He spent twenty minutes with a tape measure and still approved the proportions. That never happens.",
  "We live in a rental and needed something that felt considered, not temporary. This does. The hardware on the back is properly centred, which sounds minor until it isn’t.",
  "Texture on the oil ground is visible without being gimmicky. You can tell a hand was involved, even in a studio edition.",
  "Bought two different sizes for a hallway pair. They sit well together because the palette is consistent. That kind of editorial discipline is rare in small workshops.",
  "The gold leaf catches candlelight during gatherings. It doesn’t shout; it just holds the room. Exactly the register we wanted.",
  "Customer service answered a framing question on a Sunday evening. The piece later arrived with a written care card, which I actually kept.",
  "I collect naskh studies. This one has a quieter rhythm than the more commercial pieces circulating on Instagram. Happy to have it.",
  "Installed in a clinic waiting room. Patients comment on it, which is more than I can say for the abstract prints we used to hang.",
  "The crate was oversized for the courier, but nothing shifted inside. Paper corners, foam, and a second box — they take transit seriously.",
  "I worried the verse would feel too formal for a contemporary apartment. It doesn’t. The composition is modern enough to sit with our mid-century furniture.",
  "Medium size was the right call. Small would have been lost on that wall; large would have competed with the window. The listing photos helped, but the advice helped more.",
  "Pigment looks lightfast so far — we have had it in indirect sun for six weeks with no shift. I will update if that changes.",
  "Gave this as a wedding present. The couple displayed it in the baraat hall photos. That felt like a quiet endorsement of the work.",
  "Kufic floral work is easy to overdo. This stays disciplined. Leaves and letterforms share a weight instead of fighting each other.",
  "I am not usually sentimental about objects. This one earned a place above my desk. The line quality is confident.",
  "Ordered during a discount week. Even at full price I would buy again — the reduction was a bonus, not the reason.",
  "The stretcher bars are kiln-dried, or at least they behave like it. No bowing after a humid July in Lahore.",
  "My mother-in-law, who trained in classical scripts, paused at the letter spacing. Then she nodded. That was the review I needed.",
  "We needed a piece that would photograph well for a boutique hotel corridor. It does, from three metres and from up close.",
  "Signature on the reverse is tidy. Provenance matters to me even for contemporary studio work.",
  "The parchment ground has a slight warmth that cheap prints never get right. It looks like paper that has lived a little.",
  "I asked for a photo of the actual piece before dispatch. They sent three, in daylight. No filters. Respect.",
  "Hangs level out of the box. I still used a spirit level because I am that person. It was already true.",
  "The large canvas is heavy enough to feel substantial, light enough that two wall plugs suffice. Thoughtful engineering, not just art.",
  "We paired it with a plain ivory sofa. The gold does the talking; the furniture stays quiet. Good visual hierarchy.",
  "Bought after visiting the Instagram page for months. The physical object exceeds the feed, which is the correct order of things.",
  "Script weight is consistent across the composition. No letters collapsing at the edges, which is a common fault in rushed studio work.",
  "Our lighting designer added a picture light. The gilt responds without turning brassy. That takes a restrained palette.",
  "I returned a print from another shop last year because the blacks were dull. These blacks are ink-dark, not charcoal-grey.",
  "Placed in a law office reception. Clients assume it is an antique. We do not correct them immediately.",
  "The verse choice is familiar, but the layout is not a template. That distinction is the whole reason to buy from a specialist.",
  "Wire on the back is picture-grade, not the thin stuff that snaps in a year. Small details add up.",
  "I work long hours and wanted something still in the house when I get home. This piece does that job without demanding attention.",
  "Colour temperature under 3000K bulbs is lovely. Under daylight LEDs it stays honest. Not every canvas survives both.",
  "My daughter, who is twenty-six and allergic to ‘décor’, asked who painted it. That is a win.",
  "There is a slight impasto on the highlights. You only see it from an angle, which is how oil should behave.",
  "Ordered from Toronto. Customs paperwork was included. No surprise fees at the door, which I appreciate more than I should have to.",
  "The atelier answered in complete sentences. That sounds trivial until you have dealt with shops that reply with emojis and a tracking number.",
  "I measured the wall three times. Their size chart was accurate to the millimetre. Rare, and therefore notable.",
  "We have a cat. The lower frame has survived two months of curiosity. The finish doesn’t scratch as easily as raw wood would.",
  "Geometric work can feel cold. This one has a human pulse in the gold overlays. Hard to fake that.",
  "Bought the piece after a funeral, for a quiet room. It has been a companion rather than a statement. I did not expect that.",
  "The listing copy is understated. The object is not shy, but it isn’t loud either. Accurate marketing, for once.",
  "I commission furniture. This sits at the same standard as the walnut cabinet beside it. That is the company it should keep.",
  "Second purchase from them. The first still looks new after a year. Consistency is why I came back.",
  "The negative space around the bismillah is generous. Amateur work always fills every inch. This knows when to stop.",
  "Courier in Karachi was careful — they asked me to inspect before signing. The shop had clearly briefed them.",
  "I am sceptical of gold leaf on contemporary canvases. This application is thin, even, and aged just enough. Not costume jewellery.",
  "Hung it in a stairwell where people slow down. That is the right architecture for a piece like this.",
  "My brother thought it was a lithograph until he stood close. The surface variation gives it away, in a good way.",
  "They suggested a different verse when I described the room. I took the advice. The result feels considered, not catalogue.",
  "Frame profile is slim, which keeps the work contemporary. A heavier moulding would have pushed it toward hotel-lobby territory.",
  "I read Arabic well enough to notice a hesitant letter. There are none here. The hand is trained.",
  "We needed something for a boardroom that wasn’t a map or a slogan. Calligraphy was the adult choice. This one in particular.",
  "The unboxing felt ceremonial without being precious. Tissue, not plastic. You can tell they think about the first five minutes.",
  "I have two children under ten. The piece is high enough, and the varnish doesn’t invite fingerprints the way some oils do.",
  "Compared with a piece I bought in Istanbul in 2019, this holds its own on colour and loses slightly on paper tooth. For the price, I am more than satisfied.",
  "Evening light from the west window warms the ground. Morning light cools it. Living with it is more interesting than a static photo.",
  "The discount stacked with a product offer. Still, I judged the work on craft. The craft is there.",
  "Asked for a certificate of authenticity. It arrived signed, dated, and specific to the size. Not a generic PDF.",
  "My wife chose the piece; I handled logistics. For once we did not argue about art. That is a review in itself.",
  "The kufic panel has a garden logic rather than a poster logic. Motifs grow; they don’t stamp.",
  "Installed with gallery hooks, not nails. The wall is plaster. The piece hasn’t drifted. Good weight distribution.",
  "I travel for work. Coming home to this on the landing is a small civility I did not know I needed.",
  "Blacks, golds, and a restrained green. The palette is editorial. It will still look current in five years.",
  "They refused to rush a restock when I asked. Integrity over a sale. I waited. It was correct.",
  "The medium canvas is the sleeper size. Not too proud, not apologetic. Most living rooms want exactly this.",
  "I photographed it for our family WhatsApp. The aunties approved, which in our house is a serious metric.",
  "Surface is even — no drowning in varnish, no dry patches. Studio control is obvious.",
  "A friend who restores manuscripts looked at the script and said the proportions were classical. I trusted that more than any star rating.",
  "We painted the wall a deep olive first. This piece was chosen after, and it slots in as if the room had been waiting.",
  "Delivery to Islamabad was on a weekday morning as promised. No ‘the rider is on the way’ theatre at 10 p.m.",
  "I dislike motivational quotes dressed as art. This is scripture treated with craft. Different category entirely.",
  "The stretcher keys are present, which means I can true the canvas later if the seasons insist. Professional habit.",
  "Hung beside a family photograph from the 1970s. They speak to each other. That is harder to design than it sounds.",
  "I almost bought a cheaper print from a marketplace. The gap in presence is embarrassing. Pay for the real surface.",
  "Gold is used as light, not as luxury signalling. You feel the difference even if you cannot name it.",
  "Our housekeeper asked if she should dust it with a dry cloth. The care card already said yes. Thoughtful.",
  "I am sixty-one and tired of trends. This piece does not participate in trends. That is why it works.",
  "The large format required two people to hang. Instructions were included and were actually useful. Rare in any industry.",
  "Letter endings taper properly. That is the difference between a calligrapher and a designer using a font. This is the former.",
  "We keep the room dim in the afternoons. The piece still holds. Contrast is built into the composition, not borrowed from the lighting.",
  "Purchased after seeing a similar work in a friend’s home in DHA. Tracking down the studio took a week. Worth it.",
  "The oil has a quiet smell of linseed that faded in a day. Authentic, not chemical.",
  "I asked whether the piece was unique or an edition. They were clear. Transparency builds trust faster than adjectives.",
  "Frame corners are mitred cleanly. I ran a fingernail along the join. Nothing caught. Cabinet-maker habits die hard.",
  "This replaced a tapestry that had faded. The wall looks awake again.",
  "I work in publishing. Kerning in Latin type is my job; I still respect this spacing. Rhythm is rhythm.",
  "The small size sits on a picture ledge with books. It doesn’t compete with the spines. Good neighbour.",
  "Night-time, one lamp, this canvas. The room finally has a focal point that isn’t the television.",
  "They spelled my name correctly on the dispatch note. I notice when people don’t. I notice more when they do.",
  "Bought for a sister in Riyadh. She sent a photograph of it in her majlis. Scale was right first time.",
  "I expected a glossy finish and would have returned it. Matte was the correct decision and they stuck to it.",
  "There is a faint deckle suggestion at the painted edge, as if the ground remembers paper. Subtle, not cute.",
  "We have high ceilings. The large size still doesn’t look stranded. Composition has enough internal architecture.",
  "A teenager in the house said it was ‘actually nice’. From that demographic, this is a standing ovation.",
  "I kept the crate. If we move cities, the piece already has a proper travelling case. Forward thinking.",
  "The gold is not uniform, which is how leaf should look. Machine-flat metallic paint is a different, lesser thing.",
  "Asked them to hold the piece for collection. Studio pickup was straightforward, no theatre, tea offered, work inspected in daylight.",
  "I have ordered from calligraphers who vanish after payment. This shop confirmed, packed, and followed through. Basic competence, still rare.",
  "The verse sits slightly off-centre in a way that feels intentional. Dynamic rather than static. I like living with that tension.",
  "Wool rug below, this above. Both have a handmade grain. The room coheres.",
  "I am colour-blind to certain greens. I still read the composition clearly. Contrast was designed, not accidental.",
  "Warranty language on the site is plain. No ‘act of God’ paragraph trying to wriggle out of transit damage. Adult communication.",
  "Hung it where a previous owner had a clock. Time is still marked, just differently.",
  "The medium arrived with a barely-there scuff on the crate, none on the work. Packing margins were generous. That is how you ship art.",
  "I reread the verse in the morning sometimes. The object earns a second look, which is the point of putting words on a wall.",
  "Our designer wanted a ‘statement’. I wanted quiet. We compromised on this and both got what we needed.",
  "Black ink on a warm ground beats black ink on stark white for domestic spaces. They understand rooms, not just pages.",
  "I paid extra for insured shipping. The paperwork was real, not a checkbox. Sleeping well is part of the product.",
  "The floral motifs stay secondary to the script. Hierarchy is the whole craft. This has it.",
  "Sat with the piece for a weekend before hanging. Living with it on the floor against a wall is a good test. It passed.",
  "I have a bias toward understatement. This atelier seems to share it. We will likely buy again when a wall asks.",
  "The small format makes a remarkable gift because it doesn’t force a huge commitment of wall space. Recipients can actually use it.",
  "Edges are painted, so you don’t need a frame if you prefer a float. We framed anyway. Options are a form of respect.",
  "Someone in the family thought calligraphy was ‘old-fashioned’. They have gone quiet since it went up. Good.",
  "I checked the stretcher with a straightedge. Deviation is negligible. Studio carpentry is not an afterthought.",
  "The gold deepens after dusk. Living with a piece through different hours is the real preview, and this one changes kindly.",
  "WhatsApp updates were factual: packed, handed to courier, out for delivery. No motivational filler. Perfect.",
  "We placed it in a guest room so visitors have something humane to wake up to. Feedback has been consistent and warm.",
  "I nearly chose a busier composition. Restraint ages better. Glad they keep quieter work in the catalogue.",
  "The canvas weave is fine enough that it doesn’t fight the script. Support and image are in agreement.",
  "Bought with a store-wide discount and a product discount. Pricing still felt like art, not a clearance rack.",
  "My father stood with his hands behind his back, the way he does in museums. Then he asked the price. Then he nodded.",
  "There is no QR code, no brand splash, no ‘collection 2026’ mark on the front. The work is allowed to be the work.",
  "I requested a shade closer to our existing frames. They confirmed it would sit comfortably with walnut. It does.",
  "Humidity in Karachi is unkind to paper. Canvas was the right medium for us, and they said so before I asked.",
  "A clean, adult purchase. No countdown timers, no fake scarcity. Just a piece, a size, a price.",
  "The large work holds a fourteen-foot wall in our drawing room. I had feared a postage stamp. Scale was honest in the photographs.",
  "I like that the description didn’t oversell ‘heritage’ and ‘luxury’ in every sentence. The object does that labour.",
  "Corners of the frame are reinforced. I only know because I looked. Most buyers won’t, and they will still benefit.",
  "Installed before Eid. The house felt finished. That is a lot to ask of one rectangle, and it managed.",
  "I have returned art before when the blacks flattened in daylight. These hold. Pigment load is adequate.",
  "The studio seems to edit their own catalogue. Not everything is listed, which makes what is listed feel chosen.",
  "My partner’s parents visited from Multan and spent more time with this than with us. We will allow it.",
  "A narrow picture light was enough. You don’t need a theatre rig. The surface is generous with modest lighting.",
  "I appreciate a shop that stocks three serious sizes instead of twelve anxious ones. Decision-making stayed dignified.",
  "The script doesn’t mimic a famous historical page. It has its own tempo. Originality without novelty-seeking.",
  "Packed so well I felt guilty recycling the foam. Then I didn’t, because the next move will need it.",
  "We are not a ‘theme’ household. One strong piece is enough. This is that piece for this year.",
  "Asked whether outdoor covered corridors were suitable. They said no. I respected the boundary and kept it indoors.",
  "The invoice was itemised, including discount lines. Accounts in our office processed it without a chase. Unsung virtue.",
  "Standing two metres back, the composition locks. Standing twenty centimetres back, the craft still holds. Both distances matter.",
  "I have too much beige in the house. This introduced a necessary dark. The room finally has a bass note.",
  "They used the word ‘atelier’ on the site. For once it isn’t embarrassing. The work supports the language.",
  "Bought after a long week of looking at soulless algorithm art. This was a palate cleanser in object form.",
  "The hanging wire is twisted properly, not a single strand hoping for the best. I have opinions. They met them.",
  "A cousin in Houston ordered after seeing ours. Different piece, same standard, according to her photographs.",
  "I don’t write reviews. I am writing this because the last three art purchases disappointed me and this one did not.",
  "The ground colour sits between tea and sand. It will tolerate our curtains, which are a slightly different warm. Compatibility is a craft.",
  "Quiet luxury is an overused phrase. The object is simply well made. That is rarer and more useful.",
  "We keep books on Islamic art on the shelf below. The wall and the shelf finally agree with each other.",
  "Delivery window was a morning slot. They hit it. I did not have to take a second day off work.",
  "The piece does not smell of cheap varnish. After a day it simply smells like the room. Important in a small apartment.",
  "I asked for the depth of the stretcher before buying, to plan a float frame. The answer came with a millimetre figure. Professionals.",
  "Not every wall wants colour. This one wanted structure. Calligraphy provided it.",
  "I am glad the shop didn’t add a logo plaque. The work is signed where it should be: on the back.",
  "We hosted a dinner the night it went up. Conversation drifted to the piece and stayed there longer than the food. Unusual, welcome.",
  "The small work arrived faster than the large one I ordered later. Both were packed with the same care. Systems, not luck.",
  "There is a patience in the letterforms that you cannot rush with a deadline. You can see they didn’t.",
  "My previous calligraphy print had a plastic shine. This has a mineral quiet. Different species.",
  "I used a laser level. The top edge is straight. The universe remains ordered. Thank you.",
  "They have a point of view. Not every verse, not every colourway, not every fad. Editing is a form of respect for the buyer.",
  "Hung in a corridor that connects public rooms to private ones. It marks the threshold without a sign.",
  "I budgeted more and still felt the value when it arrived. That is the correct surprise.",
  "The photos on the product page are a touch cooler than life. In the room, warmth comes forward. I prefer the room.",
  "A good object changes how you walk through a house. I take the long way past this wall now.",
  "Frame rebate hides the canvas edge cleanly. No white flashes when you view from the side. Finish carpentry.",
  "I bought art for twenty years before this. Standards slip when you are tired. This shop did not slip.",
  "The piece is serious without being sombre. That balance is the reason it works in a family house, not only a gallery.",
  "Asked about UV glass. They explained when it helps and when it is theatre. I skipped the glass. Canvas remains honest.",
  "We moved it from the lounge to the landing after a week. It was better there. Good art survives a second thought.",
  "I don’t need a story with every purchase. The work arrived, it was as described, it hangs true. That is enough, and it is a lot.",
  "The first week it felt new. By the third it had become part of the house, which is the better outcome.",
  "I asked a carpenter friend to glance at the frame. He said the joints would outlast the wall paint. That was enough.",
  "We keep the curtains drawn against afternoon heat. Even in that quieter light the script remains fully present.",
  "A previous canvas from another maker sagged within months. This one has stayed drum-tight through a change of season.",
  "I bought it for a client and then ordered a second for myself. That is the least complicated recommendation I can give.",
  "The work does not try to impress at a glance and then collapse on inspection. It does the opposite, which is rarer.",
  "Our hallway is narrow. The medium size respects that. You can pass it without feeling lectured by a mural.",
  "I have stopped explaining the piece to guests. They usually start the conversation themselves, which is the highest compliment.",
  "The blacks stay black next to a charcoal sofa. Plenty of ‘black’ art turns blue or brown in that company. This doesn’t.",
  "Packed with a moisture barrier, which tells me they have shipped through a monsoon before. Experience shows.",
  "I kept the invoice in the same envelope as the care notes. Twenty years from now someone will be glad I did.",
  "If a house can have a voice, this is a lower register — measured, adult, and unwilling to shout.",
];

function uniqueNames(): string[] {
  const seen = new Set<string>();
  const names: string[] = [];
  for (const name of NAMES) {
    if (seen.has(name)) continue;
    seen.add(name);
    names.push(name);
  }
  return names;
}

export const REVIEW_POOL: ReviewSeed[] = (() => {
  const names = uniqueNames();
  if (names.length < 200 || BODIES.length < 200) {
    throw new Error("Review pool must contain 200 unique names and bodies");
  }

  return Array.from({ length: 200 }, (_, index) => ({
    name: names[index],
    location: LOCATIONS[index % LOCATIONS.length],
    rating: (index % 11 === 0 ? 3 : index % 3 === 0 ? 4 : 5) as 3 | 4 | 5,
    body: BODIES[index],
    daysAgo: 8 + ((index * 17) % 340),
  }));
})();
